services:

  db:
    container_name: python_de_fractal_db
    image: postgres:15
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: python_de_fractal_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d python_de_fractal_db" ]
      interval: 15s
      retries: 5
      timeout: 5s

  web:
    container_name: python_de_fractal
    build: .
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer
    container_name: python_de_fractal_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pg_data:
